name: CI

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    container: python:2.7
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_DB: notejam
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Code Analysis
      run: |
        export DJANGO_SETTINGS_MODULE=notejam.settings
        git ls-files | grep -v 'migrations' | grep -v 'settings.py' | grep -v 'manage.py' | grep -E '.py$' | xargs pylint -E --load-plugins=pylint_django
      env:
        DB_HOST: postgres
        DB_NAME: notejam
        DB_USER: user
        DB_PASSWORD: pass
    - name: Run Unit Tests
      run: |
        cd notejam
        python manage.py syncdb --noinput
        echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')" | python manage.py shell
        python manage.py migrate
        python manage.py test
      env:
        DB_HOST: postgres
        DB_NAME: notejam
        DB_USER: user
        DB_PASSWORD: pass
    - name: Run Security Tests
      run: |
        cd notejam && python manage.py check --deploy --fail-level ERROR